-- Schedule visits table for participant/admin APIs
create table if not exists public.schedule_visits (
    id bigint generated by default as identity primary key,
    "visitorName" text not null,
    "alternatePhone" text,
    "selectedDate" text not null,
    "visitTime" text not null,
    "userId" text not null,
    "propertyId" text not null,
    "propertyName" text not null,
    "createdAt" timestamptz not null default now()
);

create index if not exists idx_schedule_visits_user_id
    on public.schedule_visits ("userId");

create index if not exists idx_schedule_visits_created_at
    on public.schedule_visits ("createdAt" desc);
